name: Task manager

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0


    - name: Install Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        npm ci
        npm install -g typescript
        npm run eslint
        npm test
    
        
